import type { Metadata } from "next";
import { Geist, Geist_Mono, Joti_One, Karla } from "next/font/google";
import "./globals.css";
import ReactReduxProvider from "@/utils/providers/ReactReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jotiOne = Joti_One({
  weight: "400",
  variable: "--font-joti-one",
  subsets: ["latin"],
});

const karla = Karla({
  weight: ["400", "700"],
  variable: "--font-karla",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FamPlants - Grow ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactReduxProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${jotiOne.variable} ${karla.variable} antialiased`}
        >
          <div className="px-3 sm:px-4 md:px-6">{children}</div>
        </body>
      </html>
    </ReactReduxProvider>
  );
}
